import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";

const satoshiVariable = localFont({
  src: "../public/Fonts/Variable/Satoshi-Variable.ttf",
  variable: "--font-satoshi-variable",
});

export const metadata = {
  title: "JSCNS Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshiVariable.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
